<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Adatvédelmi Irányelvek</title>
</head>
<body>
<h3><strong>Adatv&eacute;delmi Ir&aacute;nyelvek</strong></h3>
<p><span style="font-weight: 400;">WA weboldal &eacute;s a weboldalon tal&aacute;lhat&oacute; &ouml;sszes szolg&aacute;ltat&aacute;s az </span><span style="font-weight: 400;">ABCMobile O&Uuml;</span><span style="font-weight: 400;"> &aacute;ltal &uuml;zemeltetett &eacute;s annak tulajdon&aacute;ban &aacute;ll (c&eacute;gsz&aacute;m: </span><span style="font-weight: 400;">14710834</span><span style="font-weight: 400;"> &eacute;s regisztr&aacute;lt c&iacute;me Harju maakond, Tallinn, Peterburi tee 71-318, 11415, Estonia). Az </span><span style="font-weight: 400;">ABCMobile O&Uuml;</span><span style="font-weight: 400;"> a Phone-paid Services Authority regisztr&aacute;lt tagja, amely szab&aacute;lyozza az emelt d&iacute;jas telefonszolg&aacute;ltat&aacute;sok haszn&aacute;lat&aacute;t.</span></p>
<p><span style="font-weight: 400;">Ezen szab&aacute;lyzat meghat&aacute;rozza, hogy mik&eacute;nt haszn&aacute;ljuk &eacute;s v&eacute;dj&uuml;k a weboldal haszn&aacute;lata sor&aacute;n megadott adatait. Elk&ouml;telezettek vagyunk abban, hogy biztos&iacute;tsuk a mag&aacute;n&eacute;let v&eacute;delm&eacute;t. Az &Ouml;n &aacute;ltal megadott inform&aacute;ci&oacute;kat, amelyek alapj&aacute;n &Ouml;nt azonos&iacute;tani lehet a weboldalon, a jelen adatv&eacute;delmi nyilatkozatnak megfelelően haszn&aacute;ljuk.&nbsp;</span></p>
<p><span style="font-weight: 400;">Ez a szab&aacute;lyzat a k&ouml;vetkezőket tartalmazza:</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">1. Milyen inform&aacute;ci&oacute;kat gyűjt&uuml;nk &ouml;ssze</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">2. Hogyan haszn&aacute;ljuk fel az inform&aacute;ci&oacute;kat</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">3. Az adatok t&aacute;rol&aacute;sa &eacute;s karbantart&aacute;sa</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">4. K&ouml;zz&eacute;t&eacute;tel</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">5. S&uuml;tik</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">6. Jogok</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">7. Ir&aacute;nyelveink megv&aacute;ltoztat&aacute;sa</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">8. Kapcsolattart&aacute;si adatok</span></p>
<ol>
<li><span style="font-weight: 400;"> Milyen inform&aacute;ci&oacute;kat gyűjt&uuml;nk &ouml;ssze</span></li>
</ol>
<p><span style="font-weight: 400;">Az &aacute;ltalunk gyűjt&ouml;tt inform&aacute;ci&oacute;k sz&uuml;ks&eacute;gesek ahhoz, hogy &Ouml;nnek biztos&iacute;tsuk a szolg&aacute;ltat&aacute;sunkat &eacute;s / vagy szolg&aacute;ltat&aacute;saink optimaliz&aacute;l&aacute;s&aacute;t lehetőv&eacute; tegy&eacute;k. Az ilyen inform&aacute;ci&oacute;k &ouml;sszegyűjthetők, ha ezt a weboldalt, vagy az emeltd&iacute;jas szolg&aacute;ltat&aacute;sunkat haszn&aacute;lja. Az &aacute;ltalunk gyűjt&ouml;tt inform&aacute;ci&oacute;k k&ouml;z&ouml;tt szerepelhet:&nbsp;</span></p>
<p><span style="font-weight: 400;">- N&eacute;v</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">- Nem</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">- Sz&uuml;let&eacute;si d&aacute;tum, idő</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">- Email c&iacute;m</span></p>
<p><span style="font-weight: 400;">Minden egy&eacute;b inform&aacute;ci&oacute; a weboldal űrlapjain l&aacute;that&oacute;, &eacute;s term&eacute;kenk&eacute;nt v&aacute;ltozhat. Pr&eacute;mium term&eacute;k&uuml;nk t&aacute;rolhatja a mobiltelefonsz&aacute;m&aacute;t, a t&aacute;rcs&aacute;zott sz&aacute;mot, a h&iacute;v&aacute;sok hossz&aacute;t &eacute;s gyakoris&aacute;g&aacute;t. Inform&aacute;ci&oacute;kat t&aacute;rolunk az interakci&oacute;kr&oacute;l a k&ouml;z&ouml;ss&eacute;gi m&eacute;dia platformokon vagy f&oacute;rumokon kereszt&uuml;l.</span></p>
<ol start="2">
<li><span style="font-weight: 400;"> Hogyan haszn&aacute;ljuk fel az inform&aacute;ci&oacute;kat</span></li>
</ol>
<p><span style="font-weight: 400;">Az inform&aacute;ci&oacute;kat felhaszn&aacute;ljuk, hogy:</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">- Szolg&aacute;ltat&aacute;st biztos&iacute;tsunk</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">- A szolg&aacute;ltat&aacute;st testreszabjuk</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">- Ellenőrizz&uuml;k, hogy a szolg&aacute;ltat&aacute;s ig&eacute;nybev&eacute;tel&eacute;nek korhat&aacute;r&aacute;t el&eacute;ri-e</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">- Felvegy&uuml;k &Ouml;nnel a kapcsolatot &eacute;s a h&iacute;rekről, fontos k&ouml;zlem&eacute;nyekről t&aacute;j&eacute;koztat&aacute;st k&uuml;ldj&uuml;nk (e-mailen &eacute;s / vagy SMS aj&aacute;nlatokon &eacute;s prom&oacute;ci&oacute;kon kereszt&uuml;l)</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">- Megelőzz&uuml;k a vissza&eacute;l&eacute;seket</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">- Megfelelj&uuml;nk a szab&aacute;lyoz&aacute;si k&ouml;vetelm&eacute;nyeknek</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">- Az &aacute;ltalunk ny&uacute;jtott szolg&aacute;ltat&aacute;sokat kutassuk, elemezz&uuml;k, friss&iacute;ts&uuml;k vagy fejlessz&uuml;k;&nbsp;</span></p>
<p><span style="font-weight: 400;">IHa nem szeretn&eacute; hogy kapcsolatba l&eacute;pj&uuml;nk &Ouml;nnel az aj&aacute;nlatainkkal, prom&oacute;ci&oacute;inkkal vagy h&iacute;reinkkel kapcsolatban, akkor leiratkozhat az e-mailjeinkről. A Szolg&aacute;ltat&aacute;s haszn&aacute;lat&aacute;b&oacute;l kifoly&oacute;lag fogadott vagy kezdem&eacute;nyezett h&iacute;v&aacute;sokat ellenőrizhetj&uuml;k &eacute;s felvehetj&uuml;k minős&eacute;gellenőrz&eacute;s c&eacute;lj&aacute;b&oacute;l.&nbsp;</span></p>
<ol start="3">
<li><span style="font-weight: 400;"> Az adatok t&aacute;rol&aacute;sa &eacute;s karbantart&aacute;sa</span></li>
</ol>
<p><span style="font-weight: 400;">A beny&uacute;jtott szem&eacute;lyes adatokat a szem&eacute;lyes adatok v&eacute;delm&eacute;ről sz&oacute;l&oacute; 95/45 / EK eur&oacute;pai uni&oacute;s ir&aacute;nyelvnek megfelelően az Eur&oacute;pai Gazdas&aacute;gi T&eacute;rs&eacute;gben tal&aacute;lhat&oacute; biztons&aacute;gos szerverekre k&uuml;ldj&uuml;k &eacute;s azokon t&aacute;roljuk. A beny&uacute;jtott inform&aacute;ci&oacute;kat &aacute;truh&aacute;zhatjuk a kapcsolt v&aacute;llalkoz&aacute;sainkra &eacute;s / vagy az Eur&oacute;pai Gazdas&aacute;gi T&eacute;rs&eacute;gen k&iacute;v&uuml;l eső harmadik felekre, amelyeket az Eur&oacute;pai Gazdas&aacute;gi T&eacute;rs&eacute;gen k&iacute;v&uuml;l műk&ouml;dő szem&eacute;lyzet dolgozhat fel. A weboldalon kereszt&uuml;l t&ouml;rt&eacute;nő inform&aacute;ci&oacute; elk&uuml;ld&eacute;s&eacute;vel &Ouml;n elfogadja a t&aacute;rol&aacute;st, feldolgoz&aacute;st &eacute;s / vagy &aacute;truh&aacute;z&aacute;st.&nbsp;</span></p>
<ol start="4">
<li><span style="font-weight: 400;"> Inform&aacute;ci&oacute; K&ouml;zz&eacute;t&eacute;tele</span></li>
</ol>
<p><span style="font-weight: 400;">Megoszthatjuk az &ouml;sszegyűjt&ouml;tt inform&aacute;ci&oacute;kat a kapcsolt v&aacute;llalatok k&ouml;z&ouml;tt. Időről időre m&aacute;s c&eacute;geket &eacute;s mag&aacute;nszem&eacute;lyeket is alkalmazhatunk a nev&uuml;nkben v&eacute;gzett feladatok ell&aacute;t&aacute;s&aacute;ra, bele&eacute;rtve, de nem kiz&aacute;r&oacute;lagosan a szolg&aacute;ltat&aacute;sny&uacute;jt&aacute;st, a marketingt&aacute;mogat&aacute;st, az adatelemz&eacute;st &eacute;s az &uuml;gyf&eacute;lszolg&aacute;latot, ami szem&eacute;lyes adatokhoz val&oacute; hozz&aacute;f&eacute;r&eacute;st ig&eacute;nyelhet.&nbsp;</span></p>
<p><span style="font-weight: 400;">A jogilag elő&iacute;rt inform&aacute;ci&oacute;kat nyilv&aacute;noss&aacute;gra hozzuk a szab&aacute;lyoz&oacute;- vagy az ir&aacute;ny&iacute;t&oacute; szervek sz&aacute;m&aacute;ra.&nbsp;</span></p>
<ol start="5">
<li><span style="font-weight: 400;"> S&uuml;tik</span></li>
</ol>
<p><span style="font-weight: 400;">A cookie-k lehetőv&eacute; teszik sz&aacute;munkra, hogy jobban szem&eacute;lyre szabhassuk a weboldalt a szem&eacute;lyes preferenci&aacute;k ment&eacute;se &aacute;ltal. Nem szem&eacute;lyes adatokat gyűjthet&uuml;nk &Ouml;ntől, p&eacute;ld&aacute;ul az IP-c&iacute;m&eacute;t, a b&ouml;ng&eacute;szőj&eacute;nek t&iacute;pus&aacute;t, az &Ouml;n l&aacute;togat&aacute;s&aacute;nak időtartam&aacute;t &eacute;s / vagy hossz&aacute;t, a l&aacute;togatott oldalakat &eacute;s egy&eacute;b adatokat. S&uuml;tiket haszn&aacute;lunk a weboldal l&aacute;togat&oacute;inak hiteless&eacute;gellenőrz&eacute;s&eacute;hez, szem&eacute;lyre szabott szolg&aacute;ltat&aacute;st ny&uacute;jtunk &Ouml;nnek, &eacute;s lehetőv&eacute; tessz&uuml;k a forgalomfigyel&eacute;st. A legt&ouml;bb b&ouml;ng&eacute;sző automatikusan elfogadja a cookie-kat &eacute;s a hasonl&oacute; technol&oacute;gi&aacute;kat, azonban amennyiben szeretn&eacute;, be&aacute;ll&iacute;thatja b&ouml;ng&eacute;szőj&eacute;t &uacute;gy, hogy megakad&aacute;lyozza ezt.&nbsp;</span></p>
<ol start="6">
<li><span style="font-weight: 400;"> Jogok</span></li>
</ol>
<p><span style="font-weight: 400;">&Ouml;nnek jog&aacute;ban &aacute;ll, hogy tudja, mely szem&eacute;lyes adatait t&aacute;roljuk, hogy kijav&iacute;tsa a hib&aacute;s inform&aacute;ci&oacute;kat &eacute;s megakad&aacute;lyozza, hogy szem&eacute;lyes adatait marketing c&eacute;lokra haszn&aacute;ljuk fel. K&eacute;rj&uuml;k, tov&aacute;bbi r&eacute;szletek&eacute;rt l&eacute;pjen kapcsolatba vel&uuml;nk a support@abcmobile.com c&iacute;men.&nbsp;</span></p>
<ol start="7">
<li><span style="font-weight: 400;"> Ir&aacute;nyelveink megv&aacute;ltoztat&aacute;sa</span></li>
</ol>
<p><span style="font-weight: 400;">Jogunk van b&aacute;rmikor megv&aacute;ltoztatni vagy m&oacute;dos&iacute;tani ezeket a felt&eacute;teleket. Minden v&aacute;ltoz&aacute;s, amint a webhelyre felker&uuml;l, azonnal &eacute;rv&eacute;nyes &uacute;j &eacute;s megl&eacute;vő felhaszn&aacute;l&oacute;k sz&aacute;m&aacute;ra. Ha nem &eacute;rt egyet a fel&uuml;lvizsg&aacute;lt felt&eacute;telekkel, akkor abba kell hagynia a weboldal &eacute;s annak szolg&aacute;ltat&aacute;sainak haszn&aacute;lat&aacute;t.</span></p>
<ol start="8">
<li><span style="font-weight: 400;"> Kapcsolattart&aacute;si Adatok</span></li>
</ol>
<p><span style="font-weight: 400;">Kapcsolatba l&eacute;phet vel&uuml;nk a k&ouml;vetkező c&iacute;men: support@abcmobile.com vagy postai &uacute;ton a </span><span style="font-weight: 400;">ABCMobile O&Uuml;</span><span style="font-weight: 400;">, </span><span style="font-weight: 400;">Harju maakond, Tallinn, Peterburi tee 71-318, 11415, Estonia.</span></p>
<p><br /><br /></p>




</body>
</html>